# Generated by Django 2.2.2 on 2019-12-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
